[versions]
compose = "1.4.0-dev-wasm09"
detekt = "1.23.0"
ksp = "1.9.0-1.0.11"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }