[versions]
compose = "1.4.0-dev-wasm09"
detekt = "1.23.0"
inject = "0.6.1"
kotlin = "1.9.0"
ksp = "1.9.0-1.0.11"

[libraries]
inject-compiler = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "inject" }
inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "inject" }


[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }